# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tinkoff/invest/grpc/common.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='tinkoff/invest/grpc/common.proto',
  package='tinkoff.public.invest.api.contract.v1',
  syntax='proto3',
  serialized_options=b'\n\034ru.tinkoff.piapi.contract.v1P\001Z\014./;investapi\242\002\005TIAPI\252\002\024Tinkoff.InvestApi.V1\312\002\021Tinkoff\\Invest\\V1',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n tinkoff/invest/grpc/common.proto\x12%tinkoff.public.invest.api.contract.v1\x1a\x1fgoogle/protobuf/timestamp.proto\";\n\nMoneyValue\x12\x10\n\x08\x63urrency\x18\x01 \x01(\t\x12\r\n\x05units\x18\x02 \x01(\x03\x12\x0c\n\x04nano\x18\x03 \x01(\x05\"(\n\tQuotation\x12\r\n\x05units\x18\x01 \x01(\x03\x12\x0c\n\x04nano\x18\x02 \x01(\x05\"0\n\x04Ping\x12(\n\x04time\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp*\xce\x06\n\x15SecurityTradingStatus\x12\'\n#SECURITY_TRADING_STATUS_UNSPECIFIED\x10\x00\x12\x35\n1SECURITY_TRADING_STATUS_NOT_AVAILABLE_FOR_TRADING\x10\x01\x12*\n&SECURITY_TRADING_STATUS_OPENING_PERIOD\x10\x02\x12*\n&SECURITY_TRADING_STATUS_CLOSING_PERIOD\x10\x03\x12,\n(SECURITY_TRADING_STATUS_BREAK_IN_TRADING\x10\x04\x12*\n&SECURITY_TRADING_STATUS_NORMAL_TRADING\x10\x05\x12+\n\'SECURITY_TRADING_STATUS_CLOSING_AUCTION\x10\x06\x12-\n)SECURITY_TRADING_STATUS_DARK_POOL_AUCTION\x10\x07\x12,\n(SECURITY_TRADING_STATUS_DISCRETE_AUCTION\x10\x08\x12\x32\n.SECURITY_TRADING_STATUS_OPENING_AUCTION_PERIOD\x10\t\x12<\n8SECURITY_TRADING_STATUS_TRADING_AT_CLOSING_AUCTION_PRICE\x10\n\x12,\n(SECURITY_TRADING_STATUS_SESSION_ASSIGNED\x10\x0b\x12)\n%SECURITY_TRADING_STATUS_SESSION_CLOSE\x10\x0c\x12(\n$SECURITY_TRADING_STATUS_SESSION_OPEN\x10\r\x12\x31\n-SECURITY_TRADING_STATUS_DEALER_NORMAL_TRADING\x10\x0e\x12\x33\n/SECURITY_TRADING_STATUS_DEALER_BREAK_IN_TRADING\x10\x0f\x12<\n8SECURITY_TRADING_STATUS_DEALER_NOT_AVAILABLE_FOR_TRADING\x10\x10\x42\x61\n\x1cru.tinkoff.piapi.contract.v1P\x01Z\x0c./;investapi\xa2\x02\x05TIAPI\xaa\x02\x14Tinkoff.InvestApi.V1\xca\x02\x11Tinkoff\\Invest\\V1b\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,])

_SECURITYTRADINGSTATUS = _descriptor.EnumDescriptor(
  name='SecurityTradingStatus',
  full_name='tinkoff.public.invest.api.contract.v1.SecurityTradingStatus',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SECURITY_TRADING_STATUS_UNSPECIFIED', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SECURITY_TRADING_STATUS_NOT_AVAILABLE_FOR_TRADING', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SECURITY_TRADING_STATUS_OPENING_PERIOD', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SECURITY_TRADING_STATUS_CLOSING_PERIOD', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SECURITY_TRADING_STATUS_BREAK_IN_TRADING', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SECURITY_TRADING_STATUS_NORMAL_TRADING', index=5, number=5,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SECURITY_TRADING_STATUS_CLOSING_AUCTION', index=6, number=6,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SECURITY_TRADING_STATUS_DARK_POOL_AUCTION', index=7, number=7,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SECURITY_TRADING_STATUS_DISCRETE_AUCTION', index=8, number=8,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SECURITY_TRADING_STATUS_OPENING_AUCTION_PERIOD', index=9, number=9,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SECURITY_TRADING_STATUS_TRADING_AT_CLOSING_AUCTION_PRICE', index=10, number=10,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SECURITY_TRADING_STATUS_SESSION_ASSIGNED', index=11, number=11,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SECURITY_TRADING_STATUS_SESSION_CLOSE', index=12, number=12,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SECURITY_TRADING_STATUS_SESSION_OPEN', index=13, number=13,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SECURITY_TRADING_STATUS_DEALER_NORMAL_TRADING', index=14, number=14,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SECURITY_TRADING_STATUS_DEALER_BREAK_IN_TRADING', index=15, number=15,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SECURITY_TRADING_STATUS_DEALER_NOT_AVAILABLE_FOR_TRADING', index=16, number=16,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=262,
  serialized_end=1108,
)
_sym_db.RegisterEnumDescriptor(_SECURITYTRADINGSTATUS)

SecurityTradingStatus = enum_type_wrapper.EnumTypeWrapper(_SECURITYTRADINGSTATUS)
SECURITY_TRADING_STATUS_UNSPECIFIED = 0
SECURITY_TRADING_STATUS_NOT_AVAILABLE_FOR_TRADING = 1
SECURITY_TRADING_STATUS_OPENING_PERIOD = 2
SECURITY_TRADING_STATUS_CLOSING_PERIOD = 3
SECURITY_TRADING_STATUS_BREAK_IN_TRADING = 4
SECURITY_TRADING_STATUS_NORMAL_TRADING = 5
SECURITY_TRADING_STATUS_CLOSING_AUCTION = 6
SECURITY_TRADING_STATUS_DARK_POOL_AUCTION = 7
SECURITY_TRADING_STATUS_DISCRETE_AUCTION = 8
SECURITY_TRADING_STATUS_OPENING_AUCTION_PERIOD = 9
SECURITY_TRADING_STATUS_TRADING_AT_CLOSING_AUCTION_PRICE = 10
SECURITY_TRADING_STATUS_SESSION_ASSIGNED = 11
SECURITY_TRADING_STATUS_SESSION_CLOSE = 12
SECURITY_TRADING_STATUS_SESSION_OPEN = 13
SECURITY_TRADING_STATUS_DEALER_NORMAL_TRADING = 14
SECURITY_TRADING_STATUS_DEALER_BREAK_IN_TRADING = 15
SECURITY_TRADING_STATUS_DEALER_NOT_AVAILABLE_FOR_TRADING = 16



_MONEYVALUE = _descriptor.Descriptor(
  name='MoneyValue',
  full_name='tinkoff.public.invest.api.contract.v1.MoneyValue',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='currency', full_name='tinkoff.public.invest.api.contract.v1.MoneyValue.currency', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='units', full_name='tinkoff.public.invest.api.contract.v1.MoneyValue.units', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='nano', full_name='tinkoff.public.invest.api.contract.v1.MoneyValue.nano', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=108,
  serialized_end=167,
)


_QUOTATION = _descriptor.Descriptor(
  name='Quotation',
  full_name='tinkoff.public.invest.api.contract.v1.Quotation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='units', full_name='tinkoff.public.invest.api.contract.v1.Quotation.units', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='nano', full_name='tinkoff.public.invest.api.contract.v1.Quotation.nano', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=169,
  serialized_end=209,
)


_PING = _descriptor.Descriptor(
  name='Ping',
  full_name='tinkoff.public.invest.api.contract.v1.Ping',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='time', full_name='tinkoff.public.invest.api.contract.v1.Ping.time', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=211,
  serialized_end=259,
)

_PING.fields_by_name['time'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
DESCRIPTOR.message_types_by_name['MoneyValue'] = _MONEYVALUE
DESCRIPTOR.message_types_by_name['Quotation'] = _QUOTATION
DESCRIPTOR.message_types_by_name['Ping'] = _PING
DESCRIPTOR.enum_types_by_name['SecurityTradingStatus'] = _SECURITYTRADINGSTATUS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MoneyValue = _reflection.GeneratedProtocolMessageType('MoneyValue', (_message.Message,), {
  'DESCRIPTOR' : _MONEYVALUE,
  '__module__' : 'tinkoff.invest.grpc.common_pb2'
  # @@protoc_insertion_point(class_scope:tinkoff.public.invest.api.contract.v1.MoneyValue)
  })
_sym_db.RegisterMessage(MoneyValue)

Quotation = _reflection.GeneratedProtocolMessageType('Quotation', (_message.Message,), {
  'DESCRIPTOR' : _QUOTATION,
  '__module__' : 'tinkoff.invest.grpc.common_pb2'
  # @@protoc_insertion_point(class_scope:tinkoff.public.invest.api.contract.v1.Quotation)
  })
_sym_db.RegisterMessage(Quotation)

Ping = _reflection.GeneratedProtocolMessageType('Ping', (_message.Message,), {
  'DESCRIPTOR' : _PING,
  '__module__' : 'tinkoff.invest.grpc.common_pb2'
  # @@protoc_insertion_point(class_scope:tinkoff.public.invest.api.contract.v1.Ping)
  })
_sym_db.RegisterMessage(Ping)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
