name: Bug Report
description: File a bug report
title: "[Bug] "
labels: ["bug"]
assignees:
  - daxartio
body:
  - type: markdown
    attributes:
      value: |
        Спасибо, что нашли время заполнить этот отчет об ошибке!
  - type: textarea
    id: what-happened
    attributes:
      label: Что случилось?
      description: Краткое описание
    validations:
      required: true
  - type: textarea
    id: to-reproduce
    attributes:
      label: Воспроизведение
      description: Как можно повторить кейс?
      value: |
        1. Шаг 1
        1. Шаг 2
    validations:
      required: false
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: Какая версия библиотеки используется?
      options:
        - 0.2.0-beta19
        - 0.2.0-beta18
        - 0.2.0-beta17
    validations:
      required: true
  - type: dropdown
    id: os
    attributes:
      label: OS
      description: Ваша операционная система
      options:
        - Windows
        - Linux
        - Mac OS
        - Mac OS (m1)
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Логи
      description: Скопируйте и вставьте сюда логи. Не забудьте скрыть чувствительные данные.
      render: shell
