INVEST_GRPC_API = "invest-public-api.tinkoff.ru"
APP_NAME = "tinkoff.invest-python"
X_TRACKING_ID = "x-tracking-id"
X_RATELIMIT_LIMIT = "x-ratelimit-limit"
X_RATELIMIT_REMAINING = "x-ratelimit-remaining"
X_RATELIMIT_RESET = "x-ratelimit-reset"
