INVEST_GRPC_API = "invest-public-api.tinkoff.ru"
INVEST_GRPC_API_SANDBOX = "sandbox-invest-public-api.tinkoff.ru"
APP_NAME = "tinkoff.invest-python"
X_TRACKING_ID = "x-tracking-id"
X_RATELIMIT_LIMIT = "x-ratelimit-limit"
X_RATELIMIT_REMAINING = "x-ratelimit-remaining"
X_RATELIMIT_RESET = "x-ratelimit-reset"
MESSAGE = "message"
MEGABYTE = 1024 * 1024
MAX_RECEIVE_MESSAGE_LENGTH = 10 * MEGABYTE
