"""
DO NOT EDIT!
Generated by ohmyproto
isort:skip_file
"""
import proto
from tinkoff_new.tinkoff.invest.grpc import common

__protobuf__ = proto.module(package=__name__)


class OpenSandboxAccountRequest(proto.Message):
    """Запрос открытия счёта в песочнице.
    пустой запрос
    """


class OpenSandboxAccountResponse(proto.Message):
    """Номер открытого счёта в песочнице."""

    account_id = proto.Field(proto.STRING, number=1)
    """Номер счёта"""


class CloseSandboxAccountRequest(proto.Message):
    """Запрос закрытия счёта в песочнице."""

    account_id = proto.Field(proto.STRING, number=1)
    """Номер счёта"""


class CloseSandboxAccountResponse(proto.Message):
    """Результат закрытия счёта в песочнице.
    пустой ответ
    """


class SandboxPayInRequest(proto.Message):
    """Запрос пополнения счёта в песочнице."""

    account_id = proto.Field(proto.STRING, number=1)
    """Номер счёта"""

    amount = proto.Field(common.MoneyValue, number=2)
    """Сумма пополнения счёта в рублях"""


class SandboxPayInResponse(proto.Message):
    """Результат пополнения счёта, текущий баланс."""

    balance = proto.Field(common.MoneyValue, number=1)
    """Текущий баланс счёта"""

